FROM ubuntu:24.04
# Use Ubuntu24.04 as the base image

# Tell debconf to run in non-interactive mode
ENV DEBIAN_FRONTEND noninteractive

RUN echo "-----ide env setup-----" && \
    apt-get update && apt-get install -y xorg openbox

RUN echo "-----acuity env setup-----" && \
    apt-get update && apt-get install -y gcc g++ gdb vim git htop openssh-server sudo python3 python3-pip wget make cmake unzip build-essential

# Install target packages
RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ --break-system-packages \
    html5lib \
    tensorflow==2.18.0 \
    networkx==3.3 \
    onnx==1.17.0 \
    onnxoptimizer==0.3.13 \
    onnxruntime==1.21.0 \
    dill==0.2.8.2 \
    ruamel.yaml==0.17.40 \
    ply==3.11 \
    torch==2.5.1 \
    Cython==0.29.34 \
    flatbuffers==24.3.25 \
    protobuf==3.20.3 \
    opencv-python==4.6.0.66 \
    numpy==1.26.4 \
    scipy \
    pytest \
    XlsxWriter \

RUN echo "-----user account setup-----" && \
    echo "    HostKeyAlgorithms ssh-rsa" >> /etc/ssh/ssh_config && \
    echo "    PubkeyAcceptedKeyTypes +ssh-rsa" >> /etc/ssh/ssh_config && \
    useradd -rm -d /home/builder -s /bin/bash -g root -G sudo -u 83498 builder && \
    echo 'builder:builder' | chpasswd && \
    echo 'root:root' | chpasswd

USER builder
ENV HOME /home/builder
WORKDIR /home/builder
# RUN service ssh start

EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]

# customer
# docker run -it -p 30022:22 -e DISPLAY=$IP:0 -v `pwd`:/home/builder --name acuity_ide --user builder --restart=always $IMAGE_HASH  "/bin/bash"

